# Generated by Django 4.0.3 on 2022-06-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('name', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
    ]
